#!/bin/bash
#
# Lista todos os arquivos criados no projeto
# Com descrição de cada um
#

echo ""
echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║              📚 ARQUIVOS CRIADOS - GUIA COMPLETO                      ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "📁 SCRIPTS MQL5 (Executar no MT5)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "📄 ExportHistoricalDataForTraining.mq5"
echo "   Localização: ~/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Scripts/"
echo "   Função: Coleta 500 (ou mais) candles M15 e envia para Python"
echo "   Como usar: MT5 → Tools → Scripts → ExportHistoricalDataForTraining"
echo "   Configuráveis:"
echo "      - PERIODS = 500 (mudar para 1000, 5000, etc)"
echo "      - SYMBOLS = 'EURUSD,GBPUSD,GOLD'"
echo "      - SERVER_PORT = 9999"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "🐍 SCRIPTS PYTHON (Treinamento)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "📄 train_models_from_mt5.py"
echo "   Localização: /home/ubuntu/pessoal/options/src/"
echo "   Função: Server HTTP que recebe dados do MT5 e treina modelos"
echo "   Como usar: bash /home/ubuntu/pessoal/options/bin/train_from_mt5.sh"
echo "   Ouve em: 0.0.0.0:9999"
echo "   Salva em: xgboost_*.pkl"
echo ""

echo "📄 test_training_simulation.py"
echo "   Localização: /home/ubuntu/pessoal/options/src/"
echo "   Função: Testa servidor com dados simulados"
echo "   Como usar: python3 test_training_simulation.py"
echo "   Gera: Dados fictícios para validar o sistema"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "🔍 SCRIPTS PYTHON (Análise - Ver Resultados)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "📄 analyze_models.py"
echo "   Localização: /home/ubuntu/pessoal/options/src/"
echo "   Função: Analisar modelos treinados - Feature Importance, métricas"
echo "   Como usar: python3 /home/ubuntu/pessoal/options/src/analyze_models.py"
echo "   Mostra:"
echo "      - Resumo de cada modelo"
echo "      - Feature Importance (qual indicador é mais importante)"
echo "      - Métricas detalhadas"
echo "      - Tamanho dos arquivos"
echo ""

echo "📄 test_models.py"
echo "   Localização: /home/ubuntu/pessoal/options/src/"
echo "   Função: Testar modelos com cenários simulados"
echo "   Como usar: python3 /home/ubuntu/pessoal/options/src/test_models.py"
echo "   Testa:"
echo "      - Overbought (RSI alto) - espera QUEDA"
echo "      - Oversold (RSI baixo) - espera ALTA"
echo "      - Consolidação (neutro) - sem sinal"
echo "   Mostra: Previsão, confiança, probabilidades"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "🎬 SCRIPTS BASH (Orquestração)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "📄 train_quick_start.sh"
echo "   Localização: /home/ubuntu/pessoal/options/bin/"
echo "   Função: Treinar com 3 passos simples (RECOMENDADO)"
echo "   Como usar: bash /home/ubuntu/pessoal/options/bin/train_quick_start.sh"
echo "   Faz:"
echo "      1. Inicia servidor de treinamento"
echo "      2. Aguarda você executar script no MT5"
echo "      3. Mostra resultados"
echo ""

echo "📄 train_from_mt5.sh"
echo "   Localização: /home/ubuntu/pessoal/options/bin/"
echo "   Função: Treinamento detalhado com mais controle"
echo "   Como usar: bash /home/ubuntu/pessoal/options/bin/train_from_mt5.sh"
echo "   Mostra: Progresso passo a passo"
echo ""

echo "📄 train_models_menu.sh"
echo "   Localização: /home/ubuntu/pessoal/options/bin/"
echo "   Função: Menu interativo com várias opções"
echo "   Como usar: bash /home/ubuntu/pessoal/options/bin/train_models_menu.sh"
echo "   Opções:"
echo "      1) Teste Simulado (validação)"
echo "      2) Treinamento Real (dados do MT5)"
echo "      3) Ver Documentação"
echo "      0) Sair"
echo ""

echo "📄 train_and_view.sh"
echo "   Localização: /home/ubuntu/pessoal/options/bin/"
echo "   Função: Treinar E analisar automaticamente"
echo "   Como usar: bash /home/ubuntu/pessoal/options/bin/train_and_view.sh"
echo "   Faz: Tudo em um comando"
echo ""

echo "📄 view_model_results.sh"
echo "   Localização: /home/ubuntu/pessoal/options/bin/"
echo "   Função: Apenas visualizar resultados (sem treinar)"
echo "   Como usar: bash /home/ubuntu/pessoal/options/bin/view_model_results.sh"
echo "   Mostra: Análise + testes dos modelos existentes"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "📖 DOCUMENTAÇÃO"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "📄 TREINAR_RESUMO.md"
echo "   Localização: /home/ubuntu/pessoal/options/"
echo "   Conteúdo: Resumo executivo do sistema"
echo "   Ver com: less /home/ubuntu/pessoal/options/TREINAR_RESUMO.md"
echo ""

echo "📄 TREINAR_MODELOS_DO_MT5.md"
echo "   Localização: /home/ubuntu/pessoal/options/"
echo "   Conteúdo: Guia completo (9KB, muito detalhado)"
echo "   Ver com: less /home/ubuntu/pessoal/options/TREINAR_MODELOS_DO_MT5.md"
echo "   Inclui: Troubleshooting, configuração, tudo"
echo ""

echo "📄 VER_RESULTADOS_MODELOS.md"
echo "   Localização: /home/ubuntu/pessoal/options/"
echo "   Conteúdo: Como interpretar Feature Importance, confiança, etc"
echo "   Ver com: less /home/ubuntu/pessoal/options/VER_RESULTADOS_MODELOS.md"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "📊 MODELOS TREINADOS (Gerados)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "📄 xgboost_EURUSD.pkl"
echo "   Localização: /home/ubuntu/pessoal/options/src/"
echo "   Tamanho: ~14 KB"
echo "   Criado por: train_models_from_mt5.py"
echo ""

echo "📄 xgboost_GBPUSD.pkl"
echo "   Localização: /home/ubuntu/pessoal/options/src/"
echo "   Tamanho: ~13 KB"
echo "   Criado por: train_models_from_mt5.py"
echo ""

echo "📄 xgboost_XAUUSD.pkl"
echo "   Localização: /home/ubuntu/pessoal/options/src/"
echo "   Tamanho: ~15 KB"
echo "   Criado por: train_models_from_mt5.py"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "🚀 RESUMO DE USO"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "1️⃣  TREINAR MODELOS:"
echo "    bash /home/ubuntu/pessoal/options/bin/train_quick_start.sh"
echo ""

echo "2️⃣  VER RESULTADOS (após treinar):"
echo "    python3 /home/ubuntu/pessoal/options/src/analyze_models.py"
echo "    python3 /home/ubuntu/pessoal/options/src/test_models.py"
echo ""

echo "3️⃣  USAR EM PRODUÇÃO:"
echo "    bash /home/ubuntu/pessoal/options/bin/start_system.sh"
echo "    (depois reanexar EA no MT5)"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Total: ~15 arquivos criados para treinamento + análise + produção"
echo "📦 Total size: ~50 KB (3 modelos) + scripts + docs"
echo ""
